### ISSUE TITLE
Clean task does not pass options to del command

### ISSUE THREAD

**Issue by stonecalvin** [vecnatechnologies/quick-sip#15] opened 2015-10-06 18:28 UTC
Currently the clean task is not passing in options to del (https://www.npmjs.com/package/del). This is an issue for me because I need to delete something in a folder outside of the working directory, which requires the force flag to be passed in. Also the del project has updated to use a promise API, rather than taking in the callback.

**Comment by kentmw** [comment] 2015-10-07 13:59
Duplicate of issue #9

**Closed** 2015-10-09 21:10 UTC

**Comment by mandragorn** [comment] 2015-10-09 21:12
This has been fixed by #16
